export global AppStyles {
    in-out property <length> padding: 10px;
    in-out property <length> margin: 15px;
}

export component Button {
    in-out property <string> text;
    callback clicked();
    Rectangle {
        background: ta.pressed ? #bfeafd : ta.has-hover ? #5ccbff : #449fc9;     
        // background: ta.pressed ? gray : ta.has-hover ? gray.darker(10%) : gray.darker(50%);
        animate background { duration: 100ms; }
        border-radius: 30px;
        // border-radius: 14px;
        border-width: 2px;
        border-color: self.background.darker(20%);
        ta := TouchArea {
            clicked => {
                root.clicked();
            }
        }
    }
    Text {
        text: root.text;
        color: black;
        font-size: 28px;
        font-weight: 400;
    }
}

export component ButtonOp {
    in-out property <string> text;
    callback clicked();
    Rectangle {
        background: ta.pressed ? #caffb9 : ta.has-hover ? #b9ff7c : #84c76e;     

        // background: ta.pressed ? gray : ta.has-hover ? gray.darker(10%) : gray.darker(50%);
        animate background { duration: 100ms; }
        // border-radius: 14px;
        border-radius: 30px;
        border-width: 2px;
        border-color: self.background.darker(20%);
        ta := TouchArea {
            clicked => {
                root.clicked();
            }
        }
    }
    Text {
        text: root.text;
        color: black;
        font-size: 28px;
        font-weight: 500;
    }
}
