
import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Button } from "app-styles.slint";
import { AppStyles } from "app-styles.slint";

export component AppWindow inherits Window {
    title: "Isiro";
    width: 400px;
    height: 500px;

    in-out property <string> screen;
    in-out property <string> answer;

    callback request_btn_1 <=> btn_1.clicked;
    callback request_btn_2 <=> btn_2.clicked;
    callback request_btn_3 <=> btn_3.clicked;
    callback request_btn_4 <=> btn_4.clicked;
    callback request_btn_5 <=> btn_5.clicked;
    callback request_btn_6 <=> btn_6.clicked;
    callback request_btn_7 <=> btn_7.clicked;
    callback request_btn_8 <=> btn_8.clicked;
    callback request_btn_9 <=> btn_9.clicked;
    callback request_btn_0 <=> btn_0.clicked;
    callback request_btn_cc <=> btn_cc.clicked;
    callback request_btn_dot <=> btn_dot.clicked;
    callback request_btn_plus <=> btn_plus.clicked;
    callback request_btn_minus <=> btn_minus.clicked;
    callback request_btn_mod <=> btn_mod.clicked;
    callback request_btn_div <=> btn_div.clicked;
    callback request_btn_mul <=> btn_mul.clicked;
    callback request_btn_equal <=> btn_equal.clicked;

    HorizontalBox {

        GridLayout {
            spacing: AppStyles.margin;
            padding: AppStyles.padding;

            Row {
                Text {
                    colspan: 4;
                    text: "\{screen}";
                    wrap: char-wrap;
                    font-size: 20px;
                    horizontal-alignment: right;
                    padding-bottom: 100px;
                }
            }

            Row {
                Text {
                    colspan: 4;
                    text: "\{answer}";
                    wrap: char-wrap;
                    font-size: 20px;
                    horizontal-alignment: right;
                    padding-bottom: 100px;
                }
            }

            Row {
                btn_mod := Button {
                    text: "%";
                }

                btn_div := Button {
                    text: "/";
                }

                btn_mul := Button {
                    text: "x";
                }

                btn_minus := Button {
                    text: {
                        "-";
                    }
                }
            }

            Row {
                btn_7 := Button {
                    text: {
                        7
                    }
                }

                btn_8 := Button {
                    text: {
                        8
                    }
                }

                btn_9 := Button {
                    text: {
                        9
                    }
                }

                btn_plus := Button {
                    rowspan: 2;
                    text: {
                        "+";
                    }
                }
            }

            Row {
                btn_4 := Button {
                    text: {
                        4
                    }
                }

                btn_5 := Button {
                    text: {
                        5
                    }
                }

                btn_6 := Button {
                    text: {
                        6
                    }
                }
            }

            Row {
                btn_1 := Button {
                    text: {
                        1
                    }
                }

                btn_2 := Button {
                    text: {
                        2
                    }
                }

                btn_3 := Button {
                    text: {
                        3
                    }
                }

                btn_equal := Button {
                    rowspan: 2;
                    text: {
                        "=";
                    }
                }
            }

            Row {
                btn_0 := Button {
                    text: "0";
                }

                btn_dot := Button {
                    text: ".";
                }

                btn_cc := Button {
                    text: "CC";
                }
            }
        }
    }
}
